# Form implementation generated from reading ui file 'addcatedory.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pyodbc

class Ui_Form(object):
    def __init__(self) :
        super().__init__()
        
        self.cnxn_str = (
            "Driver={SQL Server};"
            "Server=DESKTOP-JS0EJFG\SQLEXPRESS;"
            "Database=Sufi_Traders;"
            "Trusted_Connection=yes;"
        )
        self.id = 0
        self.idfind()
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setGeometry(QtCore.QRect(170, 70, 113, 24))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(70, 70, 71, 16))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(250, 150, 80, 24))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(170, 110, 113, 24))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(70, 110, 91, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit.setText('{}'.format(str(self.id)))
        self.lineEdit.setEnabled(False)
        self.lineEdit_2.setFocus()

        self.pushButton.clicked.connect(self.addcategory)
        self.lineEdit.returnPressed.connect(lambda: self.lineEdit_2.setFocus())

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Category ID"))
        self.pushButton.setText(_translate("Form", "ADD"))
        self.label_2.setText(_translate("Form", "Category ID"))
    
    def idfind(self):
        try:
            # Assign the connection to cnxn
            cnxn = pyodbc.connect(self.cnxn_str)
            with cnxn.cursor() as cursor:
                cursor.execute("Select MAX(categoryID) From Categories")
                row = cursor.fetchone()
                if row:
                    self.id = row[0] + 1
                else:
                    self.id = 1
        except pyodbc.Error as ex:
            pass
        finally:
            # Close the connection in the finally block
            if cnxn:
                cnxn.close()
    def addcategory(self):
        cnxn = None
        cid = self.lineEdit.text()
        cname = self.lineEdit_2.text()
        try:
            # Assign the connection to cnxn
            cnxn = pyodbc.connect(self.cnxn_str)
            with cnxn.cursor() as cursor:
                cursor.execute("Insert into Categories values (?,?)", cid,cname)
                cursor.commit()
                msg_box = QtWidgets.QMessageBox()
                msg_box.setWindowTitle("Success")
                msg_box.setText("Category added successfully .")
                msg_box.setIcon(QtWidgets.QMessageBox.Icon.Information)
                msg_box.setStandardButtons(QtWidgets.QMessageBox.StandardButton.Ok)
                result = msg_box.exec()
        except pyodbc.Error as ex:
            msg_box = QtWidgets.QMessageBox()
            msg_box.setWindowTitle("Error")
            msg_box.setText("{}".format(ex))
            msg_box.setIcon(QtWidgets.QMessageBox.Icon.Critical)
            msg_box.setStandardButtons(QtWidgets.QMessageBox.StandardButton.Ok)
            result = msg_box.exec()
        finally:
            # Close the connection in the finally block
            if cnxn:
                cnxn.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
