# Form implementation generated from reading ui file 'findsupplier.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pyodbc

class Ui_Form(object):
    def __init__(self): 
        self.cnxn_str = (
            "Driver={SQL Server};"
            "Server=MALIK-TALHA;"
            "Database=Sufi_Traders;"
            "Trusted_Connection=yes;"
        )
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(78, 110, 81, 20))
        self.label.setObjectName("label")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(200, 190, 113, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(78, 150, 91, 20))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 150, 113, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setGeometry(QtCore.QRect(200, 110, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(80, 190, 101, 20))
        self.label_3.setObjectName("label_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(200, 230, 113, 22))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(80, 230, 101, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(40, 50, 321, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit.returnPressed.connect(self.findbyid)
        self.lineEdit_2.returnPressed.connect(self.findbyname)
        self.lineEdit_3.returnPressed.connect(self.findbycontact)
        self.lineEdit.setFocus()
        self.lineEdit_4.setEnabled(False)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Supplier ID"))
        self.label_2.setText(_translate("Form", "Supplier Name"))
        self.label_3.setText(_translate("Form", "Supplier Contact"))
        self.label_4.setText(_translate("Form", "Supplier Address"))
        self.label_5.setText(_translate("Form", "Enter any detail and PRESS Enter to get details"))

    def findbyid(self):
        id = self.lineEdit.text()
        cnxn = None
        try:
            with pyodbc.connect(self.cnxn_str) as conn:
                cursor = conn.cursor()
                cursor.execute(
                    "SELECT * FROM Supplier WHERE supplierID = ?", id
                )
                row = cursor.fetchone()
                if row:
                    self.lineEdit_2.setText(row[1])
                    self.lineEdit_3.setText(row[3])
                    self.lineEdit_4.setText(row[2])
                else:
                    msg = QtWidgets.QMessageBox()
                    msg.setWindowTitle("Error")
                    msg.setText("Supplier Not Found")
                    msg.setIcon(QtWidgets.QMessageBox.Icon.Critical)
                    msg.setStandardButtons(QtWidgets.QMessageBox.StandardButton.Ok)
                    msg.exec()
        except pyodbc.Error as ex:
            msg = QtWidgets.QMessageBox()
            msg.setWindowTitle("Error")
            msg.setText("Database Error: {}".format(ex))
            msg.setIcon(QtWidgets.QMessageBox.Icon.Critical)
            msg.setStandardButtons(QtWidgets.QMessageBox.StandardButton.Ok)
            msg.exec()
        finally:
            if cnxn:
                cnxn.close()
    def findbyname(self):
        name = self.lineEdit_2.text()
        cnxn = None
        try:
            with pyodbc.connect(self.cnxn_str) as conn:
                cursor = conn.cursor()
                cursor.execute(
                    "SELECT * FROM Supplier WHERE supplierName = ?", name
                )
                row = cursor.fetchone()
                if row:
                    self.lineEdit.setText(str(row[0]))
                    self.lineEdit_3.setText(str(row[3]))
                    self.lineEdit_4.setText(str(row[2]))
                else:
                    msg_box = QtWidgets.QMessageBox()
                    msg_box.setWindowTitle("Error")
                    msg_box.setText("No Supplier Found")
                    msg_box.setIcon(QtWidgets.QMessageBox.Icon.Critical)
                    msg_box.setStandardButtons(QtWidgets.QMessageBox.StandardButton.Ok)
                    result = msg_box.exec()
        except pyodbc.Error as ex:
            msg_box = QtWidgets.QMessageBox()
            msg_box.setWindowTitle("Database Error")
            msg_box.setText("Error: {}".format(ex))
            msg_box.setIcon(QtWidgets.QMessageBox.Icon.Critical)
            msg_box.setStandardButtons(QtWidgets.QMessageBox.StandardButton.Ok)
            result = msg_box.exec()
        finally:
            if cnxn:
                cnxn.close()
    def findbycontact(self):
        contact = self.lineEdit_3.text()
        cnxn = None
        try:
            with pyodbc.connect(self.cnxn_str) as conn:
                cursor = conn.cursor()
                cursor.execute(
                    "SELECT * FROM Supplier WHERE supplierContact = ?", contact
                )
                row = cursor.fetchone()
                if row:
                    self.lineEdit.setText(str(row[0]))
                    self.lineEdit_2.setText(str(row[1]))
                    self.lineEdit_4.setText(str(row[2]))
                else:
                    msg_box = QtWidgets.QMessageBox()
                    msg_box.setWindowTitle("Error")
                    msg_box.setText("No Supplier Found")
                    msg_box.setIcon(QtWidgets.QMessageBox.Icon.Critical)
                    msg_box.setStandardButtons(QtWidgets.QMessageBox.StandardButton.Ok)
                    result = msg_box.exec()
        except pyodbc.Error as ex:
            msg_box = QtWidgets.QMessageBox()
            msg_box.setWindowTitle("Database Error")
            msg_box.setText("Error: {}".format(ex))
            msg_box.setIcon(QtWidgets.QMessageBox.Icon.Critical)
            msg_box.setStandardButtons(QtWidgets.QMessageBox.StandardButton.Ok)
            result = msg_box.exec()
        finally:
            if cnxn:
                cnxn.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
