# Form implementation generated from reading ui file 'updateemployee.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pyodbc
from db import DatabaseManager
class Ui_Form(object):
    def __init__(self):
        self.db = DatabaseManager()
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(371, 342)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(60, 150, 91, 20))
        self.label_2.setObjectName("label_2")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(160, 230, 113, 24))
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(58, 70, 71, 20))
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 150, 113, 24))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(60, 110, 71, 20))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setGeometry(QtCore.QRect(160, 70, 113, 24))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(160, 190, 113, 24))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 110, 113, 24))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(60, 190, 71, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(60, 230, 71, 20))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(240, 290, 80, 24))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(160, 30, 113, 24))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(60, 30, 71, 20))
        self.label_7.setObjectName("label_7")
        self.lineEdit_6.setFocus()
        self.lineEdit_6.returnPressed.connect(self.findemp)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Update Employee Details"))
        self.label_2.setText(_translate("Form", "Contact Number"))
        self.label.setText(_translate("Form", "First Name"))
        self.label_3.setText(_translate("Form", "Last Name"))
        self.label_4.setText(_translate("Form", "Address"))
        self.label_5.setText(_translate("Form", "Salary"))
        self.pushButton.setText(_translate("Form", "Update"))
        self.label_7.setText(_translate("Form", "Employee ID"))
    def findemp(self):
        rows = self.db.execute_read_query("SELECT * FROM Employee WHERE employeeID = '{}'".format(self.lineEdit_6.text()))
        if rows:
            for row in rows:
                self.lineEdit.setText(row[1])
                self.lineEdit_3.setText(row[2])
                self.lineEdit_2.setText(row[3])
                self.lineEdit_4.setText(row[4])
                self.lineEdit_5.setText(str(row[5]))
                self.lineEdit_6.setEnabled(False)
                self.lineEdit.setFocus()
                self.pushButton.clicked.connect(self.updateemp)
        else:
            msg_box = QtWidgets.QMessageBox()
            msg_box.setIcon(QtWidgets.QMessageBox.Icon.Warning)
            msg_box.setStandardButtons(QtWidgets.QMessageBox.StandardButton.Ok)
            msg_box.setText("Employee not found!")
            msg_box.setWindowTitle("Error")
            msg_box.exec()

    def updateemp(self):
        self.db.execute_query("UPDATE Employee SET empFName = '{}', empLName = '{}', employeeAddress = '{}', empContact = '{}', salary = '{}' WHERE employeeID = '{}'".format(self.lineEdit.text(), self.lineEdit_3.text(), self.lineEdit_2.text(), self.lineEdit_4.text(), self.lineEdit_5.text(), self.lineEdit_6.text()))
        msg_box = QtWidgets.QMessageBox()
        msg_box.setIcon(QtWidgets.QMessageBox.Icon.Information)
        msg_box.setStandardButtons(QtWidgets.QMessageBox.StandardButton.Ok)
        msg_box.setText("Employee updated successfully!")
        msg_box.setWindowTitle("Success")
        msg_box.exec()
        Form.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
